version: '3'
services:
  #################################基础设施######################################## 
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./infrastructure/mysql/conf.d:/etc/mysql/conf.d
      - ./infrastructure/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
      - ./infrastructure/mysql/data:/var/lib/mysql
      - ./infrastructure/mysql/log:/var/log/mysql
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379/tcp
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - ./infrastructure/prometheus/data:/prometheus-data
    command: --config.file=/prometheus-data/prometheus.yml
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411/tcp

  #################################微服务######################################## 
  books:
    build: ./books
    image: books:1.0
    container_name: books
    depends_on:
      - mysql
      - redis
      - prometheus
      - zipkin
    ports:
      - 5001:5001
      - 5002:5002
      - 5003:5003
      - 5004:5004
      - 5005:5005

  comments:
    build: ./comments
    image: comments:1.0
    container_name: comments
    depends_on:
      - mysql
      - redis
      - prometheus
      - zipkin
    ports:
      - 5011:5001
      - 5012:5002
      - 5013:5003
      - 5014:5004
      - 5015:5005

